DROP TABLE IF EXISTS TELEFONE;
DROP TABLE IF EXISTS USUARIO;
CREATE TABLE USUARIO(ID LONG AUTO_INCREMENT PRIMARY KEY,  FIRST_NAME VARCHAR(255) NOT NULL, LAST_NAME VARCHAR(255) NOT NULL, SENHA VARCHAR(255) NOT NULL, 
EMAIL VARCHAR(255) NOT NULL, LAST_LOGIN DATETIME ,CREATED_AT DATETIME, CREATED_BY LONG, UPDATED_AT DATETIME, UPDATED_BY LONG);

CREATE TABLE TELEFONE(ID LONG AUTO_INCREMENT PRIMARY KEY, USUARIO_ID LONG NOT NULL, NUMBER LONG NOT NULL, AREA LONG NOT NULL, COUNTRY_CODE VARCHAR(10) NOT NULL, CREATED_AT DATETIME, CREATED_BY LONG, UPDATED_AT DATETIME, UPDATED_BY LONG);
ALTER TABLE TELEFONE 
ADD FOREIGN KEY (USUARIO_ID) 
REFERENCES USUARIO(ID);